[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  command = "npm run dev"
  targetPort = 3005
  port = 8888
  framework = "#custom"
  functions = "functions"
